### PR TITLE
Don't use path.join for URLs

### LINKED ISSUE #25: Backslashes mess up revision activation on Windows
Plugin fails to activate revisions on S3 when used on Windows environments. I am using Windows 10 x64. When creating a query for S3 the key for identifying filenames on S3 contains backslashes and the process fails with following error:

InvalidArgument: Copy Source must mention the source bucket and key: sourcebucket/sourcekey

For everyone encountering the same issue with version 0.1.0 there is a quick and dirty fix. Edit the file ember-cli-deploy-s3-index/lib/s3.js and replace the following line:

`var copySource  = encodeURIComponent(path.join(bucket, revisionKey);`
with
`var copySource  = encodeURIComponent(path.join(bucket, revisionKey).replace('\\','/'));`

### PR DESCRIPTION
**Pull request by LevelbossMike**
If we rely on `path.join` to join strings with '/' we break
the plugin for windows users as `path.join` inserts `\\` instead
of `/` on windows.

Fixes #25

### CODE REVIEW

**Comment by LevelbossMike** [comment]
Please wait for @fedakim, @davidbilling or @DanielJurkovic to confirm that this fixes their problem on windows before merging

File: lib/s3.js [hunk 1]
```diff
@@ -21,6 +21,10 @@ var headObject = function(client, params) {
   });
 }
 
+function addPrefixToURI(prefix, uri) {
```
Comment (lukemelia) [inline lib/s3.js]: Maybe `joinUriSegments` would be a better name?

Comment (LevelbossMike) [inline lib/s3.js]: Great input! thx!

**Comment by davidbilling** [comment]
@LevelbossMike Yes, your fix works on my windows! Great! =)

**Comment by LevelbossMike** [comment]
Great to hear! Does everything work as expected? `deploy`, `activate` & `list` command (also with a prefix option set)? I can't test on windows unfortunately.

**Comment by davidbilling** [comment]
Yes, deploy activate and list. Have not tested prefix...

**Comment by ghedamat** [comment]
@LevelbossMike good to merge?

**Comment by carlosgalveias** [comment]
works for me :)

2016-01-19 12:57 GMT+00:00 Mattia Gheda notifications@github.com:

**Comment by davidbilling** [comment]
Works for me too :)

**Comment by lukemelia** [comment]
Thanks for the confirmations @davidbilling and @fedakim, and good job implementing @LevelbossMike!
